//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductQuoteApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProductQuoteApp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string ActBack {
            get {
                return ResourceManager.GetString("ActBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver al Listado.
        /// </summary>
        public static string ActBackToList {
            get {
                return ResourceManager.GetString("ActBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Contraseña.
        /// </summary>
        public static string ActChangePassword {
            get {
                return ResourceManager.GetString("ActChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string ActCreate {
            get {
                return ResourceManager.GetString("ActCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear y Salir.
        /// </summary>
        public static string ActCreateAndQuit {
            get {
                return ResourceManager.GetString("ActCreateAndQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string ActDelete {
            get {
                return ResourceManager.GetString("ActDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ActDetails {
            get {
                return ResourceManager.GetString("ActDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ActEdit {
            get {
                return ResourceManager.GetString("ActEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grabar.
        /// </summary>
        public static string ActSave {
            get {
                return ResourceManager.GetString("ActSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Code_Description {
            get {
                return ResourceManager.GetString("Code_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el Código.
        /// </summary>
        public static string Code_Required {
            get {
                return ResourceManager.GetString("Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificación Crediticia.
        /// </summary>
        public static string CreditRating {
            get {
                return ResourceManager.GetString("CreditRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Clasificación Crediticia.
        /// </summary>
        public static string CreditRatingID_Required {
            get {
                return ResourceManager.GetString("CreditRatingID_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Tipo Moneda.
        /// </summary>
        public static string CurrencyType_Required {
            get {
                return ResourceManager.GetString("CurrencyType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Description_Description {
            get {
                return ResourceManager.GetString("Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Descripción.
        /// </summary>
        public static string Description_Required {
            get {
                return ResourceManager.GetString("Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción debe ser menor a 200 caracteres.
        /// </summary>
        public static string Description200_Long {
            get {
                return ResourceManager.GetString("Description200_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle debe ser menor a 2048 caracteres.
        /// </summary>
        public static string Details2048_Long {
            get {
                return ResourceManager.GetString("Details2048_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string EtyBrand {
            get {
                return ResourceManager.GetString("EtyBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca no debe tener mas de 200 caracteres.
        /// </summary>
        public static string EtyBrand_Long {
            get {
                return ResourceManager.GetString("EtyBrand_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Marca.
        /// </summary>
        public static string EtyBrand_Required {
            get {
                return ResourceManager.GetString("EtyBrand_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string EtyContact {
            get {
                return ResourceManager.GetString("EtyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clase Contacto.
        /// </summary>
        public static string EtyContactClass {
            get {
                return ResourceManager.GetString("EtyContactClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string EtyContacts {
            get {
                return ResourceManager.GetString("EtyContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Contacto.
        /// </summary>
        public static string EtyContactType {
            get {
                return ResourceManager.GetString("EtyContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificación Crediticia.
        /// </summary>
        public static string EtyCreditRating {
            get {
                return ResourceManager.GetString("EtyCreditRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Moneda (ARS/USD).
        /// </summary>
        public static string EtyCurrencyType {
            get {
                return ResourceManager.GetString("EtyCurrencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string EtyCustomer {
            get {
                return ResourceManager.GetString("EtyCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string EtyCustomerOrderStatus {
            get {
                return ResourceManager.GetString("EtyCustomerOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string EtyCustomers {
            get {
                return ResourceManager.GetString("EtyCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Carga.
        /// </summary>
        public static string EtyFreightType {
            get {
                return ResourceManager.GetString("EtyFreightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Carga.
        /// </summary>
        public static string EtyFreightTypes {
            get {
                return ResourceManager.GetString("EtyFreightTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar de Entrega.
        /// </summary>
        public static string EtyGeographicArea {
            get {
                return ResourceManager.GetString("EtyGeographicArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugares de Entrega.
        /// </summary>
        public static string EtyGeographicAreas {
            get {
                return ResourceManager.GetString("EtyGeographicAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros del Sistema.
        /// </summary>
        public static string EtyGlobalVariables {
            get {
                return ResourceManager.GetString("EtyGlobalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratamiento IIBB.
        /// </summary>
        public static string EtyIIBBTreatment {
            get {
                return ResourceManager.GetString("EtyIIBBTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envase.
        /// </summary>
        public static string EtyPackaging {
            get {
                return ResourceManager.GetString("EtyPackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envases.
        /// </summary>
        public static string EtyPackagings {
            get {
                return ResourceManager.GetString("EtyPackagings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición de Pago.
        /// </summary>
        public static string EtyPaymentDeadline {
            get {
                return ResourceManager.GetString("EtyPaymentDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones de Pago.
        /// </summary>
        public static string EtyPaymentDeadlines {
            get {
                return ResourceManager.GetString("EtyPaymentDeadlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string EtyProduct {
            get {
                return ResourceManager.GetString("EtyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        public static string EtyProductDocuments {
            get {
                return ResourceManager.GetString("EtyProductDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotización Producto.
        /// </summary>
        public static string EtyProductQuote {
            get {
                return ResourceManager.GetString("EtyProductQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotizaciones Productos.
        /// </summary>
        public static string EtyProductQuotes {
            get {
                return ResourceManager.GetString("EtyProductQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string EtyProducts {
            get {
                return ResourceManager.GetString("EtyProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        public static string EtyProvider {
            get {
                return ResourceManager.GetString("EtyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        public static string EtyProviders {
            get {
                return ResourceManager.GetString("EtyProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivos de Cierre.
        /// </summary>
        public static string EtyReasonsForClosure {
            get {
                return ResourceManager.GetString("EtyReasonsForClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotización Dólar Futuro.
        /// </summary>
        public static string EtyRofexs {
            get {
                return ResourceManager.GetString("EtyRofexs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidad de Venta.
        /// </summary>
        public static string EtySaleModality {
            get {
                return ResourceManager.GetString("EtySaleModality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negocio.
        /// </summary>
        public static string EtySalesChannel {
            get {
                return ResourceManager.GetString("EtySalesChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Vendedora.
        /// </summary>
        public static string EtySellerCompany {
            get {
                return ResourceManager.GetString("EtySellerCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Transporte.
        /// </summary>
        public static string EtyTransportType {
            get {
                return ResourceManager.GetString("EtyTransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Transporte.
        /// </summary>
        public static string EtyTransportTypes {
            get {
                return ResourceManager.GetString("EtyTransportTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string EtyUser {
            get {
                return ResourceManager.GetString("EtyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string EtyUsers {
            get {
                return ResourceManager.GetString("EtyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductQuoteTemplate_es.pdf.
        /// </summary>
        public static string FileNamePdfProductQuoteTemplate {
            get {
                return ResourceManager.GetString("FileNamePdfProductQuoteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un valor numérico.
        /// </summary>
        public static string GralNumberValue {
            get {
                return ResourceManager.GetString("GralNumberValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un valor entre 0,0 y 100,0.
        /// </summary>
        public static string GralPercentageValue {
            get {
                return ResourceManager.GetString("GralPercentageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Min.
        /// </summary>
        public static string MargenMin {
            get {
                return ResourceManager.GetString("MargenMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Margen Min.
        /// </summary>
        public static string MargenMin_Required {
            get {
                return ResourceManager.GetString("MargenMin_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Name_Name {
            get {
                return ResourceManager.GetString("Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Nombre.
        /// </summary>
        public static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre debe ser menor a 200 caracteres.
        /// </summary>
        public static string Name200_Long {
            get {
                return ResourceManager.GetString("Name200_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones debe ser menor a 200 caracteres.
        /// </summary>
        public static string Obs500_Long {
            get {
                return ResourceManager.GetString("Obs500_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kg Envase.
        /// </summary>
        public static string PackagingKilogram {
            get {
                return ResourceManager.GetString("PackagingKilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Kg Envase.
        /// </summary>
        public static string PackagingKilogram_Required {
            get {
                return ResourceManager.GetString("PackagingKilogram_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Mínima de Venta (Kg.).
        /// </summary>
        public static string PositionKilogram {
            get {
                return ResourceManager.GetString("PositionKilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Unidad Mínima de Venta (Kg.).
        /// </summary>
        public static string PositionKilogram_Required {
            get {
                return ResourceManager.GetString("PositionKilogram_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string PtyActive {
            get {
                return ResourceManager.GetString("PtyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a todos los Clientes.
        /// </summary>
        public static string PtyAddToAllCustomer {
            get {
                return ResourceManager.GetString("PtyAddToAllCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar Precio Proporcional o Margen Equivalente.
        /// </summary>
        public static string PtyApplyPriceFactor {
            get {
                return ResourceManager.GetString("PtyApplyPriceFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibilidad (Dias).
        /// </summary>
        public static string PtyAvailabilityDays {
            get {
                return ResourceManager.GetString("PtyAvailabilityDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Compra-Venta Directa.
        /// </summary>
        public static string PtyBuyAndSellDirect {
            get {
                return ResourceManager.GetString("PtyBuyAndSellDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones Cliente.
        /// </summary>
        public static string PtyClientObservations {
            get {
                return ResourceManager.GetString("PtyClientObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Cierre.
        /// </summary>
        public static string PtyClosureDate {
            get {
                return ResourceManager.GetString("PtyClosureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Fecha Cierre.
        /// </summary>
        public static string PtyClosureDate_Required {
            get {
                return ResourceManager.GetString("PtyClosureDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones Cierre.
        /// </summary>
        public static string PtyClosureObservations {
            get {
                return ResourceManager.GetString("PtyClosureObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string PtyCompany {
            get {
                return ResourceManager.GetString("PtyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Ingresar Empresa.
        /// </summary>
        public static string PtyCompany_Required {
            get {
                return ResourceManager.GetString("PtyCompany_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa debe ser menor a 200 caracteres.
        /// </summary>
        public static string PtyCompany200_Long {
            get {
                return ResourceManager.GetString("PtyCompany200_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completado.
        /// </summary>
        public static string PtyCompleted {
            get {
                return ResourceManager.GetString("PtyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación contraseña nueva.
        /// </summary>
        public static string PtyConfirmNewPassword {
            get {
                return ResourceManager.GetString("PtyConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Confirmación contraseña nueva.
        /// </summary>
        public static string PtyConfirmNewPassword_Required {
            get {
                return ResourceManager.GetString("PtyConfirmNewPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nueva contraseña y la confirmación no coinciden.
        /// </summary>
        public static string PtyConfirmNewPasswordCompare {
            get {
                return ResourceManager.GetString("PtyConfirmNewPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        public static string PtyConfirmPassword {
            get {
                return ResourceManager.GetString("PtyConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la Confirmación de Contraseña.
        /// </summary>
        public static string PtyConfirmPassword_Required {
            get {
                return ResourceManager.GetString("PtyConfirmPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Contraseña y la Confirmación no coinciden.
        /// </summary>
        public static string PtyConfirmPasswordNoMatch {
            get {
                return ResourceManager.GetString("PtyConfirmPasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo Almacenamiento (ARS/Mes/Posición).
        /// </summary>
        public static string PtyCostoAlmacenamientoMensual {
            get {
                return ResourceManager.GetString("PtyCostoAlmacenamientoMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Costo Almac. (ARS/Mes/Posición).
        /// </summary>
        public static string PtyCostoAlmacenamientoMensual_Required {
            get {
                return ResourceManager.GetString("PtyCostoAlmacenamientoMensual_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo Finananciero (TEM %).
        /// </summary>
        public static string PtyCostoFinancieroMensual {
            get {
                return ResourceManager.GetString("PtyCostoFinancieroMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Costo Finananciero (TEM %).
        /// </summary>
        public static string PtyCostoFinancieroMensual_Required {
            get {
                return ResourceManager.GetString("PtyCostoFinancieroMensual_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo IN-OUT (ARS/Posición).
        /// </summary>
        public static string PtyCostoInOut {
            get {
                return ResourceManager.GetString("PtyCostoInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Costo IN-OUT (ARS/Posición).
        /// </summary>
        public static string PtyCostoInOut_Required {
            get {
                return ResourceManager.GetString("PtyCostoInOut_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual.
        /// </summary>
        public static string PtyCurrentPassword {
            get {
                return ResourceManager.GetString("PtyCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Contraseña actual.
        /// </summary>
        public static string PtyCurrentPassword_Required {
            get {
                return ResourceManager.GetString("PtyCurrentPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Administrador?.
        /// </summary>
        public static string PtyCustomerAdmin {
            get {
                return ResourceManager.GetString("PtyCustomerAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string PtyCustomerName {
            get {
                return ResourceManager.GetString("PtyCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto debe ser menor a 200 caracteres.
        /// </summary>
        public static string PtyCustomerName_Long {
            get {
                return ResourceManager.GetString("PtyCustomerName_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Contacto.
        /// </summary>
        public static string PtyCustomerName_Required {
            get {
                return ResourceManager.GetString("PtyCustomerName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string PtyCustomerOrderCode {
            get {
                return ResourceManager.GetString("PtyCustomerOrderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string PtyCustomerOrderDateOrder {
            get {
                return ResourceManager.GetString("PtyCustomerOrderDateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Fecha Contacto.
        /// </summary>
        public static string PtyDateContact_Required {
            get {
                return ResourceManager.GetString("PtyDateContact_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Entrega.
        /// </summary>
        public static string PtyDateDelivery {
            get {
                return ResourceManager.GetString("PtyDateDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Cotización.
        /// </summary>
        public static string PtyDateQuote {
            get {
                return ResourceManager.GetString("PtyDateQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechas de Entrega.
        /// </summary>
        public static string PtyDatesDeliveryInput {
            get {
                return ResourceManager.GetString("PtyDatesDeliveryInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Enviada.
        /// </summary>
        public static string PtyDateSent {
            get {
                return ResourceManager.GetString("PtyDateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días.
        /// </summary>
        public static string PtyDays {
            get {
                return ResourceManager.GetString("PtyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Días.
        /// </summary>
        public static string PtyDays_Required {
            get {
                return ResourceManager.GetString("PtyDays_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de Entregas.
        /// </summary>
        public static string PtyDeliveryAmount {
            get {
                return ResourceManager.GetString("PtyDeliveryAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Cantidad de Entregas.
        /// </summary>
        public static string PtyDeliveryAmount_Required {
            get {
                return ResourceManager.GetString("PtyDeliveryAmount_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string PtyDescription {
            get {
                return ResourceManager.GetString("PtyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dias Stock Promedio Dist. Local.
        /// </summary>
        public static string PtyDiasStockPromedioDistLocal {
            get {
                return ResourceManager.GetString("PtyDiasStockPromedioDistLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotización Dolar.
        /// </summary>
        public static string PtyDollarQuotation {
            get {
                return ResourceManager.GetString("PtyDollarQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edita Parametros?.
        /// </summary>
        public static string PtyEditGlobalVariables {
            get {
                return ResourceManager.GetString("PtyEditGlobalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edita Margen y/o Precio?.
        /// </summary>
        public static string PtyEditMarginOrPrice {
            get {
                return ResourceManager.GetString("PtyEditMarginOrPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PtyEmail {
            get {
                return ResourceManager.GetString("PtyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Email.
        /// </summary>
        public static string PtyEmail_Required {
            get {
                return ResourceManager.GetString("PtyEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Estimada.
        /// </summary>
        public static string PtyEstimatedDate {
            get {
                return ResourceManager.GetString("PtyEstimatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de Excepcion.
        /// </summary>
        public static string PtyExceptionPrice {
            get {
                return ResourceManager.GetString("PtyExceptionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo Seguro Cambiario (% sobre Precio).
        /// </summary>
        public static string PtyExchangeInsurance {
            get {
                return ResourceManager.GetString("PtyExchangeInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda de la Operación.
        /// </summary>
        public static string PtyExchangeType {
            get {
                return ResourceManager.GetString("PtyExchangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor Tiempo en Stock.
        /// </summary>
        public static string PtyFactorCostoAlmacenamientoMensual {
            get {
                return ResourceManager.GetString("PtyFactorCostoAlmacenamientoMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Factor Tiempo en Stock.
        /// </summary>
        public static string PtyFactorCostoAlmacenamientoMensual_Required {
            get {
                return ResourceManager.GetString("PtyFactorCostoAlmacenamientoMensual_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad por Contenedor (Kg).
        /// </summary>
        public static string PtyFCLKilogram {
            get {
                return ResourceManager.GetString("PtyFCLKilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Cantidad por Contenedor (Kg).
        /// </summary>
        public static string PtyFCLKilogram_Required {
            get {
                return ResourceManager.GetString("PtyFCLKilogram_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string PtyFirstName {
            get {
                return ResourceManager.GetString("PtyFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Nombre.
        /// </summary>
        public static string PtyFirstName_Required {
            get {
                return ResourceManager.GetString("PtyFirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Carga.
        /// </summary>
        public static string PtyFreightType {
            get {
                return ResourceManager.GetString("PtyFreightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastos Fijos (%).
        /// </summary>
        public static string PtyGastosFijos {
            get {
                return ResourceManager.GetString("PtyGastosFijos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Gastos Fijos (%).
        /// </summary>
        public static string PtyGastosFijos_Required {
            get {
                return ResourceManager.GetString("PtyGastosFijos_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El largo del campo no debe superar los 200 caracteres.
        /// </summary>
        public static string PtyGralLong_200 {
            get {
                return ResourceManager.GetString("PtyGralLong_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El largo del campo no debe superar los 50 caracteres.
        /// </summary>
        public static string PtyGralLong_50 {
            get {
                return ResourceManager.GetString("PtyGralLong_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIBB Alicuota (%).
        /// </summary>
        public static string PtyIIBBAlicuota {
            get {
                return ResourceManager.GetString("PtyIIBBAlicuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar IIBB (%) Alicuota.
        /// </summary>
        public static string PtyIIBBAlicuota_Required {
            get {
                return ResourceManager.GetString("PtyIIBBAlicuota_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto Débito/Credito (%).
        /// </summary>
        public static string PtyImpuestoDebitoCredito {
            get {
                return ResourceManager.GetString("PtyImpuestoDebitoCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Impuesto Débito/Credito (%).
        /// </summary>
        public static string PtyImpuestoDebitoCredito_Required {
            get {
                return ResourceManager.GetString("PtyImpuestoDebitoCredito_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciales.
        /// </summary>
        public static string PtyInitials {
            get {
                return ResourceManager.GetString("PtyInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar las Iniciales.
        /// </summary>
        public static string PtyInitials_Required {
            get {
                return ResourceManager.GetString("PtyInitials_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar 3 caracteres.
        /// </summary>
        public static string PtyInitials_Rule {
            get {
                return ResourceManager.GetString("PtyInitials_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacenamiento In/Out.
        /// </summary>
        public static string PtyInOutStorage {
            get {
                return ResourceManager.GetString("PtyInOutStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los valores deben ser entre 1 y 100.
        /// </summary>
        public static string PtyIntRange1_100 {
            get {
                return ResourceManager.GetString("PtyIntRange1_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los valores deben ser entre 1 y 1.000.000.
        /// </summary>
        public static string PtyIntRange1_1000000 {
            get {
                return ResourceManager.GetString("PtyIntRange1_1000000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Administrador?.
        /// </summary>
        public static string PtyIsCustomerAdmin {
            get {
                return ResourceManager.GetString("PtyIsCustomerAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de Entregas de Busqueda?.
        /// </summary>
        public static string PtyIsDeliveryAmountSearchParam {
            get {
                return ResourceManager.GetString("PtyIsDeliveryAmountSearchParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda de la Operacion de Busqueda?.
        /// </summary>
        public static string PtyIsExchangeTypeSearchParam {
            get {
                return ResourceManager.GetString("PtyIsExchangeTypeSearchParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar de Entrega de Busqueda?.
        /// </summary>
        public static string PtyIsGeographicAreaSearchParam {
            get {
                return ResourceManager.GetString("PtyIsGeographicAreaSearchParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo Tiempo en Stock (Meses) de Busqueda?.
        /// </summary>
        public static string PtyIsMaximumMonthsStockSearchParam {
            get {
                return ResourceManager.GetString("PtyIsMaximumMonthsStockSearchParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Minima por Entrega de Busqueda?.
        /// </summary>
        public static string PtyIsMinimumQuantityDeliverySearchParam {
            get {
                return ResourceManager.GetString("PtyIsMinimumQuantityDeliverySearchParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición de Pago de Busqueda?.
        /// </summary>
        public static string PtyIsPaymentDeadlineSearchParam {
            get {
                return ResourceManager.GetString("PtyIsPaymentDeadlineSearchParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Prostecto.
        /// </summary>
        public static string PtyIsProspect {
            get {
                return ResourceManager.GetString("PtyIsProspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Total  Orden de Compra (Kg) de Busqueda?.
        /// </summary>
        public static string PtyIsQuantityOpenPurchaseOrderSearchParam {
            get {
                return ResourceManager.GetString("PtyIsQuantityOpenPurchaseOrderSearchParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidad de Venta de Busqueda?.
        /// </summary>
        public static string PtyIsSaleModalitySearchParam {
            get {
                return ResourceManager.GetString("PtyIsSaleModalitySearchParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente Spot.
        /// </summary>
        public static string PtyIsSpot {
            get {
                return ResourceManager.GetString("PtyIsSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string PtyJobPosition {
            get {
                return ResourceManager.GetString("PtyJobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string PtyLastName {
            get {
                return ResourceManager.GetString("PtyLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Apellido.
        /// </summary>
        public static string PtyLastName_Required {
            get {
                return ResourceManager.GetString("PtyLastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Time (Días desde FACT).
        /// </summary>
        public static string PtyLeadTime {
            get {
                return ResourceManager.GetString("PtyLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo Tiempo en Stock (Meses).
        /// </summary>
        public static string PtyMaximumMonthsStock {
            get {
                return ResourceManager.GetString("PtyMaximumMonthsStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merma Granel (%).
        /// </summary>
        public static string PtyMermaGranel {
            get {
                return ResourceManager.GetString("PtyMermaGranel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Merma Granel (%).
        /// </summary>
        public static string PtyMermaGranel_Required {
            get {
                return ResourceManager.GetString("PtyMermaGranel_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Mínimo General (%).
        /// </summary>
        public static string PtyMinimumMarginGeneralPercentage {
            get {
                return ResourceManager.GetString("PtyMinimumMarginGeneralPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el Margen Mínimo General (%).
        /// </summary>
        public static string PtyMinimumMarginGeneralPercentage_Required {
            get {
                return ResourceManager.GetString("PtyMinimumMarginGeneralPercentage_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Mínimo General (USD).
        /// </summary>
        public static string PtyMinimumMarginGeneralUSD {
            get {
                return ResourceManager.GetString("PtyMinimumMarginGeneralUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el Margen Mínimo General (USD).
        /// </summary>
        public static string PtyMinimumMarginGeneralUSD_Required {
            get {
                return ResourceManager.GetString("PtyMinimumMarginGeneralUSD_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Mínimo Operación (%).
        /// </summary>
        public static string PtyMinimumMarginPercentage {
            get {
                return ResourceManager.GetString("PtyMinimumMarginPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Mínimo (Distribución Local) (%).
        /// </summary>
        public static string PtyMinimumMarginPercentage_DL {
            get {
                return ResourceManager.GetString("PtyMinimumMarginPercentage_DL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Mínimo (Distribución con Importación a Pedido) (%).
        /// </summary>
        public static string PtyMinimumMarginPercentage_DLP {
            get {
                return ResourceManager.GetString("PtyMinimumMarginPercentage_DLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Mínimo (Indent) (%).
        /// </summary>
        public static string PtyMinimumMarginPercentage_IND {
            get {
                return ResourceManager.GetString("PtyMinimumMarginPercentage_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Mínimo (Indent + Servicio Logístico/Financiero) (%).
        /// </summary>
        public static string PtyMinimumMarginPercentage_ISL {
            get {
                return ResourceManager.GetString("PtyMinimumMarginPercentage_ISL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el Margen Mínimo Operación  (%).
        /// </summary>
        public static string PtyMinimumMarginPercentage_Required {
            get {
                return ResourceManager.GetString("PtyMinimumMarginPercentage_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Mínimo por Entrega (USD).
        /// </summary>
        public static string PtyMinimumMarginUSD {
            get {
                return ResourceManager.GetString("PtyMinimumMarginUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Mínimo (Distribución Local) (USD).
        /// </summary>
        public static string PtyMinimumMarginUSD_DL {
            get {
                return ResourceManager.GetString("PtyMinimumMarginUSD_DL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Mínimo (Distribución con Importación a Pedido) (USD).
        /// </summary>
        public static string PtyMinimumMarginUSD_DLP {
            get {
                return ResourceManager.GetString("PtyMinimumMarginUSD_DLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Mínimo (Indent) (USD).
        /// </summary>
        public static string PtyMinimumMarginUSD_IND {
            get {
                return ResourceManager.GetString("PtyMinimumMarginUSD_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen Mínimo (Indent + Servicio Logístico/Financiero) (USD).
        /// </summary>
        public static string PtyMinimumMarginUSD_ISL {
            get {
                return ResourceManager.GetString("PtyMinimumMarginUSD_ISL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar el Margen Mínimo por Entrega (USD).
        /// </summary>
        public static string PtyMinimumMarginUSD_Required {
            get {
                return ResourceManager.GetString("PtyMinimumMarginUSD_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meses.
        /// </summary>
        public static string PtyMonths {
            get {
                return ResourceManager.GetString("PtyMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string PtyName {
            get {
                return ResourceManager.GetString("PtyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña nueva.
        /// </summary>
        public static string PtyNewPassword {
            get {
                return ResourceManager.GetString("PtyNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Contraseña nueva.
        /// </summary>
        public static string PtyNewPassword_Required {
            get {
                return ResourceManager.GetString("PtyNewPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string PtyObservation {
            get {
                return ResourceManager.GetString("PtyObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string PtyObservations {
            get {
                return ResourceManager.GetString("PtyObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado OC.
        /// </summary>
        public static string PtyOCStatus {
            get {
                return ResourceManager.GetString("PtyOCStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string PtyPassword {
            get {
                return ResourceManager.GetString("PtyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar la Contraseña.
        /// </summary>
        public static string PtyPassword_Required {
            get {
                return ResourceManager.GetString("PtyPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Contraseña debe tener al menos 6 caracteres de largo.
        /// </summary>
        public static string PtyPassword_Rule {
            get {
                return ResourceManager.GetString("PtyPassword_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener al menos 6 caracteres.
        /// </summary>
        public static string PtyPasswordRules {
            get {
                return ResourceManager.GetString("PtyPasswordRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje.
        /// </summary>
        public static string PtyPercentage {
            get {
                return ResourceManager.GetString("PtyPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neto Min. (Kg).
        /// </summary>
        public static string PtyPositionQuantityFrom {
            get {
                return ResourceManager.GetString("PtyPositionQuantityFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Neto Min. (Kg).
        /// </summary>
        public static string PtyPositionQuantityFrom_Required {
            get {
                return ResourceManager.GetString("PtyPositionQuantityFrom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neto Max (Kg).
        /// </summary>
        public static string PtyPositionQuantityTo {
            get {
                return ResourceManager.GetString("PtyPositionQuantityTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Neto Max (Kg).
        /// </summary>
        public static string PtyPositionQuantityTo_Required {
            get {
                return ResourceManager.GetString("PtyPositionQuantityTo_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template PDF Cotizacion.
        /// </summary>
        public static string PtyPQPDFTemplate {
            get {
                return ResourceManager.GetString("PtyPQPDFTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Template PDF Cotizacion.
        /// </summary>
        public static string PtyPQPDFTemplate_Required {
            get {
                return ResourceManager.GetString("PtyPQPDFTemplate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template PDF Cotizacion debe ser menor a 200 caracteres.
        /// </summary>
        public static string PtyPQPDFTemplate200_Long {
            get {
                return ResourceManager.GetString("PtyPQPDFTemplate200_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template PDF Reducido Cotizacion.
        /// </summary>
        public static string PtyPQSmallPDFTemplate {
            get {
                return ResourceManager.GetString("PtyPQSmallPDFTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Template PDF Reducido Cotizacion.
        /// </summary>
        public static string PtyPQSmallPDFTemplate_Required {
            get {
                return ResourceManager.GetString("PtyPQSmallPDFTemplate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template PDF Reducido Cotizacion debe ser menor a 200 caracteres.
        /// </summary>
        public static string PtyPQSmallPDFTemplate200_Long {
            get {
                return ResourceManager.GetString("PtyPQSmallPDFTemplate200_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio (USD/Kg).
        /// </summary>
        public static string PtyPrice {
            get {
                return ResourceManager.GetString("PtyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe Total por Entrega (USD).
        /// </summary>
        public static string PtyPrice_PorEntrega {
            get {
                return ResourceManager.GetString("PtyPrice_PorEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe Total Orden de Compra (USD).
        /// </summary>
        public static string PtyPrice_PorOC {
            get {
                return ResourceManager.GetString("PtyPrice_PorOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Original.
        /// </summary>
        public static string PtyPriceOriginal {
            get {
                return ResourceManager.GetString("PtyPriceOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Compra/Venta Directa?.
        /// </summary>
        public static string PtyProductBuyAndSellDirect {
            get {
                return ResourceManager.GetString("PtyProductBuyAndSellDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo (Distribución Local).
        /// </summary>
        public static string PtyProductCost_DL {
            get {
                return ResourceManager.GetString("PtyProductCost_DL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo (Distribución con Importación a Pedido).
        /// </summary>
        public static string PtyProductCost_DLP {
            get {
                return ResourceManager.GetString("PtyProductCost_DLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo (Indent).
        /// </summary>
        public static string PtyProductCost_IND {
            get {
                return ResourceManager.GetString("PtyProductCost_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo (Indent + Servicio Logístico/Financiero).
        /// </summary>
        public static string PtyProductCost_ISL {
            get {
                return ResourceManager.GetString("PtyProductCost_ISL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string PtyProductDocumentPDF {
            get {
                return ResourceManager.GetString("PtyProductDocumentPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cargar un Documento.
        /// </summary>
        public static string PtyProductDocumentPDF_Required {
            get {
                return ResourceManager.GetString("PtyProductDocumentPDF_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotización Producto.
        /// </summary>
        public static string PtyProductQuoteCode {
            get {
                return ResourceManager.GetString("PtyProductQuoteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Proveedor.
        /// </summary>
        public static string PtyProviderName {
            get {
                return ResourceManager.GetString("PtyProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plazo Pago Proveedores (Días).
        /// </summary>
        public static string PtyProviderPaymentDeadline {
            get {
                return ResourceManager.GetString("PtyProviderPaymentDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Plazo Pago Proveedores (Días).
        /// </summary>
        public static string PtyProviderPaymentDeadline_Required {
            get {
                return ResourceManager.GetString("PtyProviderPaymentDeadline_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Mínima por Entrega (Kg).
        /// </summary>
        public static string PtyQuantity {
            get {
                return ResourceManager.GetString("PtyQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Total  Orden de Compra (Kg).
        /// </summary>
        public static string PtyQuantityOpenPurchaseOrder {
            get {
                return ResourceManager.GetString("PtyQuantityOpenPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Cantidad Total  Orden de Compra (Kg).
        /// </summary>
        public static string PtyQuantityOpenPurchaseOrder_Required {
            get {
                return ResourceManager.GetString("PtyQuantityOpenPurchaseOrder_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotización a Revisar.
        /// </summary>
        public static string PtyQuoteToRevision {
            get {
                return ResourceManager.GetString("PtyQuoteToRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Real.
        /// </summary>
        public static string PtyRealDate {
            get {
                return ResourceManager.GetString("PtyRealDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordarme?.
        /// </summary>
        public static string PtyRememberMe {
            get {
                return ResourceManager.GetString("PtyRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ve Costeo?.
        /// </summary>
        public static string PtySeeCosting {
            get {
                return ResourceManager.GetString("PtySeeCosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apilable.
        /// </summary>
        public static string PtyStackable {
            get {
                return ResourceManager.GetString("PtyStackable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apilable.
        /// </summary>
        public static string PtyStackeable {
            get {
                return ResourceManager.GetString("PtyStackeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string PtyStateName {
            get {
                return ResourceManager.GetString("PtyStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Medio Stock Meses.
        /// </summary>
        public static string PtyTiempoMedioStockMeses {
            get {
                return ResourceManager.GetString("PtyTiempoMedioStockMeses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Cambio (ARS/USD).
        /// </summary>
        public static string PtyTipoCambio {
            get {
                return ResourceManager.GetString("PtyTipoCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Tipo Cambio (ARS/USD).
        /// </summary>
        public static string PtyTipoCambio_Required {
            get {
                return ResourceManager.GetString("PtyTipoCambio_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string PtyUserName {
            get {
                return ResourceManager.GetString("PtyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validez Precio.
        /// </summary>
        public static string PtyValidityOfPrice {
            get {
                return ResourceManager.GetString("PtyValidityOfPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Validez del Precio.
        /// </summary>
        public static string PtyValidityOfPrice_Required {
            get {
                return ResourceManager.GetString("PtyValidityOfPrice_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merma Producto (%).
        /// </summary>
        public static string PtyWaste {
            get {
                return ResourceManager.GetString("PtyWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Merma (%).
        /// </summary>
        public static string PtyWaste_Required {
            get {
                return ResourceManager.GetString("PtyWaste_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Cantidad Mínima por Entrega (Kg).
        /// </summary>
        public static string Quantity_Required {
            get {
                return ResourceManager.GetString("Quantity_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta usted seguro de eliminar.
        /// </summary>
        public static string QuestionDelete {
            get {
                return ResourceManager.GetString("QuestionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comisión Vendedor (%).
        /// </summary>
        public static string SellerCommission {
            get {
                return ResourceManager.GetString("SellerCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Comisión Vendedor (%).
        /// </summary>
        public static string SellerCommission_Required {
            get {
                return ResourceManager.GetString("SellerCommission_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validez Precio.
        /// </summary>
        public static string ValidityPeriodOfPrice {
            get {
                return ResourceManager.GetString("ValidityPeriodOfPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Validez Precio.
        /// </summary>
        public static string ValidityPeriodOfPrice_Required {
            get {
                return ResourceManager.GetString("ValidityPeriodOfPrice_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo en Depósito (USD/Kg).
        /// </summary>
        public static string WarehouseCost {
            get {
                return ResourceManager.GetString("WarehouseCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Costo en Depósito (USD/Kg).
        /// </summary>
        public static string WarehouseCost_Required {
            get {
                return ResourceManager.GetString("WarehouseCost_Required", resourceCulture);
            }
        }
    }
}
